services:
    postgres:
        container_name: postgres
        image: postgres:16-alpine
        volumes:
            - postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: keycloak
            POSTGRES_USER: keycloak
            POSTGRES_PASSWORD: password
    keycloak:
        container_name: keycloak
        image: quay.io/keycloak/keycloak:22.0
        environment:
            # keycloak settings
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
            KEYCLOAK_LOGLEVEL: INFO
            ROOT_LOGLEVEL: INFO
            # database
            KC_DB: postgres
            KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
            KC_DB_USERNAME: keycloak
            KC_DB_PASSWORD: password
        ports:
            - 8080:8080
        depends_on:
            - postgres
        command: start-dev

volumes:
    postgres:
        driver: local
